### ISSUE TITLE
Overlay bug

### ISSUE THREAD

**Issue by Z1xus** [Kix48/OpenSpades-Internal#3]
It does work but I can't see the overlay, only for a half a second when switching windows. Running on Windows 10, compiled with Visual Studio 2022

**Comment by Kix48** [comment]
Make sure the correct window width and height are set in Overlay.cpp. Also, make sure you don’t have the game in full screen. I have not touched this project in 2 years so I can’t recall if the game even has this option. If these don’t fix the issue, try to read and understand the code enough to be able to debug it. I hope this helps!
